name: streamlit_nana_tutorial

services:
  # 1. The Database Container
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mlops-network

  # 2. The Database UI Container
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
    ports:
      - "8083:8081"
    networks:
      - mlops-network

  # 3. Your Custom Python App Container
  streamlit-app:
    build: .
    container_name: streamlit-dev
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
    ports:
      - "8501:8501"
    networks:
      - mlops-network

volumes:
  mongo-data:

networks:
  mlops-network:
    name: streamlit_nana_tutorial_mlops-network
    external: true
